// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apputil} from '../models';

export function ErrorMsg(arg1:string,arg2:string):Promise<void>;

export function InfoMsg(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<apputil.MsgEmity>;

export function QuestionMsg(arg1:string,arg2:string):Promise<string>;

export function ReadFile(arg1:string):Promise<apputil.MsgEmity>;

export function ReadInit():Promise<void>;

export function ReadNowFile():Promise<apputil.MsgEmity>;

export function SaveAsFile(arg1:string,arg2:string):Promise<apputil.MsgEmity>;

export function SaveFile(arg1:string,arg2:string):Promise<apputil.MsgEmity>;

export function SecondInstanceLaunch():Promise<void>;

export function WarningMsg(arg1:string,arg2:string):Promise<void>;

export function WindowPrint():Promise<string>;
