// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorMsg(arg1, arg2) {
  return window['go']['main']['App']['ErrorMsg'](arg1, arg2);
}

export function InfoMsg(arg1, arg2) {
  return window['go']['main']['App']['InfoMsg'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function QuestionMsg(arg1, arg2) {
  return window['go']['main']['App']['QuestionMsg'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadInit() {
  return window['go']['main']['App']['ReadInit']();
}

export function ReadNowFile() {
  return window['go']['main']['App']['ReadNowFile']();
}

export function SaveAsFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAsFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SecondInstanceLaunch() {
  return window['go']['main']['App']['SecondInstanceLaunch']();
}

export function WarningMsg(arg1, arg2) {
  return window['go']['main']['App']['WarningMsg'](arg1, arg2);
}

export function WindowPrint() {
  return window['go']['main']['App']['WindowPrint']();
}
